SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
AMMO_RADIUS = 4
PADDLE_THICKNESS = 40
PADDLE_WIDTH = 120
PADDLE_Y_FROM_BOTTOM = 40
ANSWER_WIDTH = 100

PADDLE_TOP = SCREEN_HEIGHT - PADDLE_Y_FROM_BOTTOM - PADDLE_THICKNESS / 2
